### ISSUE TITLE
Does not match across files

### ISSUE THREAD

**Issue by dwelle** [konstantinkobs/brackets-LESShints#2]
It would be nice if variable autocompletion worked across files that are either:

- currently opened (working files)
- reside in the same project folder

My team tends to have most of the variables in a separate file so the extension is rather unusable at this time.

**Comment by christraverse** [comment]
Just adding my voice to this.  Would love to be able to use cross file variables as most of the building blocks for my sites are contained in separate less files.

**Comment by retan** [comment]
I would appreciate something similar too.
I'm sure if searching all less through all less files is a good idea - I might slow Brackets considerably.
But at least the opened files or files imported into the current one.

**Comment by konstantinkobs** [comment]
Hey guys, I finally got time to implement this feature! So now you'll get hints for all variables in all of the LESS files in your project!

I hope you like this update! :wink:
